# Generated by Django 5.2.4 on 2025-07-17 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTPEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('issuer', models.CharField(blank=True, max_length=100)),
                ('encrypted_secret', models.BinaryField()),
                ('digits', models.PositiveSmallIntegerField(default=6)),
                ('period', models.PositiveSmallIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
